from __future__ import annotations

import argparse
import json
from pathlib import Path

from fairy_core.contracts.methods import CORE_METHODS, CoreMethodTransport


def _manifest() -> dict[str, object]:
    return {
        "schema_version": 1,
        "methods": [
            {
                "name": name,
                "transport": method.transport.value,
                "request_model": method.request_model.__name__,
                "response_model": method.response_model.__name__,
            }
            for name, method in sorted(CORE_METHODS.items())
        ],
    }


def _typescript() -> str:
    rows = [
        f'  "{name}": "{method.transport.value}",' for name, method in sorted(CORE_METHODS.items())
    ]
    local_only = [
        f'  "{name}",'
        for name, method in sorted(CORE_METHODS.items())
        if method.transport is CoreMethodTransport.LOCAL_ONLY
    ]
    return "\n".join(
        [
            "// Generated by cloud/scripts/export_rpc_manifest.py. Do not edit.",
            "export const CORE_METHOD_TRANSPORT = {",
            *rows,
            '} as const satisfies Record<string, "local_only" | "local_and_cloud">;',
            "",
            "export const LOCAL_ONLY_CORE_METHODS = [",
            *local_only,
            "] as const;",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Export the canonical Fairy RPC method catalog")
    parser.add_argument("manifest", type=Path)
    parser.add_argument("typescript", type=Path)
    arguments = parser.parse_args()

    arguments.manifest.parent.mkdir(parents=True, exist_ok=True)
    arguments.manifest.write_text(
        json.dumps(_manifest(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    arguments.typescript.parent.mkdir(parents=True, exist_ok=True)
    arguments.typescript.write_text(_typescript(), encoding="utf-8")


if __name__ == "__main__":
    main()
