from __future__ import annotations

from typing import Protocol
from uuid import UUID

from fairy_core.domain.execution import Approval, Changeset, Checkpoint
from fairy_core.domain.models import Conversation, Project, Task, Version


class StateStore(Protocol):
    def save_project(self, project: Project) -> None: ...

    def get_project(self, project_id: UUID) -> Project | None: ...

    def save_conversation(self, conversation: Conversation) -> None: ...

    def get_conversation(self, conversation_id: UUID) -> Conversation | None: ...

    def save_version(self, version: Version) -> None: ...

    def get_version(self, version_id: UUID) -> Version | None: ...

    def save_task(self, task: Task, *, idempotency_key: str | None = None) -> None: ...

    def get_task(self, task_id: UUID) -> Task | None: ...

    def find_task_by_idempotency_key(self, idempotency_key: str) -> Task | None: ...

    def save_changeset(self, changeset: Changeset) -> None: ...

    def get_changeset(self, changeset_id: UUID) -> Changeset | None: ...

    def find_changeset_by_idempotency_key(self, idempotency_key: str) -> Changeset | None: ...

    def changesets_for_task(self, task_id: UUID) -> list[Changeset]: ...

    def save_approval(self, approval: Approval) -> None: ...

    def get_approval(self, approval_id: UUID) -> Approval | None: ...

    def find_approval_by_changeset_id(self, changeset_id: UUID) -> Approval | None: ...

    def save_checkpoint(self, checkpoint: Checkpoint) -> None: ...

    def get_checkpoint(self, checkpoint_id: UUID) -> Checkpoint | None: ...

    def accept_version(
        self,
        *,
        project_id: UUID,
        version_id: UUID,
        expected_revision: int,
    ) -> Project: ...

    def close(self) -> None: ...
