from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict

JsonValue = str | int | float | bool | None | list[Any] | dict[str, Any]


class ContractModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        from_attributes=True,
        use_enum_values=False,
    )


class ExecutionTarget(StrEnum):
    LOCAL = "local"
    CLOUD = "cloud"


class PermissionProfileModel(StrEnum):
    OBSERVE = "observe"
    STANDARD = "standard"
    AUTONOMOUS = "autonomous"


class EventVisibilityModel(StrEnum):
    USER = "user"
    DEVELOPER = "developer"
    INTERNAL = "internal"


class PublicMessageVisibilityModel(StrEnum):
    USER = "user"
    DEVELOPER = "developer"


class ErrorCode(StrEnum):
    PATH_OUT_OF_SCOPE = "PATH_OUT_OF_SCOPE"
    PATH_IDENTITY_CHANGED = "PATH_IDENTITY_CHANGED"
    SCOPE_MISMATCH = "SCOPE_MISMATCH"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    SANDBOX_UNAVAILABLE = "SANDBOX_UNAVAILABLE"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    SECRET_EGRESS_BLOCKED = "SECRET_EGRESS_BLOCKED"
    CAPABILITY_NOT_AVAILABLE = "CAPABILITY_NOT_AVAILABLE"
    WORKER_INTERRUPTED = "WORKER_INTERRUPTED"
    PROJECT_BUSY = "PROJECT_BUSY"
    MEMORY_SCOPE_VIOLATION = "MEMORY_SCOPE_VIOLATION"
    MEMORY_CONFLICT = "MEMORY_CONFLICT"
    MEMORY_INJECTION_BLOCKED = "MEMORY_INJECTION_BLOCKED"
    MEMORY_SECRET_BLOCKED = "MEMORY_SECRET_BLOCKED"
    MEMORY_PROJECTION_STALE = "MEMORY_PROJECTION_STALE"
    MEMORY_SNAPSHOT_TOO_LARGE = "MEMORY_SNAPSHOT_TOO_LARGE"
    MEMORY_FORGOTTEN = "MEMORY_FORGOTTEN"
    DOCUMENT_PROJECTION_STALE = "DOCUMENT_PROJECTION_STALE"
    DOCUMENT_INTEGRITY_FAILED = "DOCUMENT_INTEGRITY_FAILED"
    MCP_CAPABILITY_MISSING = "MCP_CAPABILITY_MISSING"
    MCP_CREDENTIAL_UNAVAILABLE = "MCP_CREDENTIAL_UNAVAILABLE"
    MCP_DESTINATION_BLOCKED = "MCP_DESTINATION_BLOCKED"
    MCP_OUTPUT_INVALID = "MCP_OUTPUT_INVALID"
    MCP_OUTPUT_UNSUPPORTED = "MCP_OUTPUT_UNSUPPORTED"
    MCP_PROTOCOL_MISMATCH = "MCP_PROTOCOL_MISMATCH"
    MCP_RESULT_UNCERTAIN = "MCP_RESULT_UNCERTAIN"
    MCP_SCHEMA_CHANGED = "MCP_SCHEMA_CHANGED"
    MCP_SCHEMA_INVALID = "MCP_SCHEMA_INVALID"
    MCP_TOOL_ERROR = "MCP_TOOL_ERROR"
    MCP_TRANSPORT_INTERRUPTED = "MCP_TRANSPORT_INTERRUPTED"
    MCP_TRANSPORT_NOT_ALLOWED = "MCP_TRANSPORT_NOT_ALLOWED"
    MCP_UNAVAILABLE = "MCP_UNAVAILABLE"
    FORMAT_UNSUPPORTED = "FORMAT_UNSUPPORTED"
    PACK_REQUIRED = "PACK_REQUIRED"
    PACK_UNTRUSTED = "PACK_UNTRUSTED"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_ENCRYPTED = "FILE_ENCRYPTED"
    ACTIVE_CONTENT_BLOCKED = "ACTIVE_CONTENT_BLOCKED"
    DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
    CONVERSION_TIMEOUT = "CONVERSION_TIMEOUT"
    DERIVATIVE_INVALID = "DERIVATIVE_INVALID"
    FIDELITY_DEGRADED = "FIDELITY_DEGRADED"
    CACHE_QUOTA_EXCEEDED = "CACHE_QUOTA_EXCEEDED"
    EDIT_NOT_EXPORTABLE = "EDIT_NOT_EXPORTABLE"


__all__ = [
    "ContractModel",
    "ErrorCode",
    "EventVisibilityModel",
    "ExecutionTarget",
    "JsonValue",
    "PermissionProfileModel",
    "PublicMessageVisibilityModel",
]
