from __future__ import annotations


REINDEX_ELIGIBLE = "REINDEX_ELIGIBLE"
REINDEX_FAILED = "REINDEX_FAILED"
REINDEX_COMPLETED_WITH_ERRORS = "REINDEX_COMPLETED_WITH_ERRORS"
DECISION_PENDING_TOO_LONG = "DECISION_PENDING_TOO_LONG"
EMBEDDING_CHANGED_NOT_REINDEXED = "EMBEDDING_CHANGED_NOT_REINDEXED"
VECTOR_BACKEND_DEGRADED = "VECTOR_BACKEND_DEGRADED"

ACTION_REQUIRED = "action_required"
CRITICAL = "critical"
SUGGESTION = "suggestion"
INFO = "info"

MANAGED_NOTIFICATION_TYPES = {
    REINDEX_ELIGIBLE,
    REINDEX_FAILED,
    REINDEX_COMPLETED_WITH_ERRORS,
    DECISION_PENDING_TOO_LONG,
    EMBEDDING_CHANGED_NOT_REINDEXED,
    VECTOR_BACKEND_DEGRADED,
}
